print("-----------------------------------------")
print("   YXETweaks: Connection Successful!     ")
print("-----------------------------------------")
print("[+] The loader is working perfectly.")
input("\nPress ENTER to close...")